### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by JoshuaRileyDev** [guikeller/cordova-watchconnectivity-plugin#2]
Can you publish this plugin to NPM so it can be used in a CapacitorJS project?

**Comment by guy-keller** [comment]
Hi @JoshuaRileyDev ,

Thanks for the suggestion, can you please try and do this here instead:
```
npm install https://github.com/guikeller/cordova-watchconnectivity-plugin.git 
npx cap sync
```

To use the plugin on your ts service.
```
declare var WatchConnectivity;
```

Source / More info here:
https://stackoverflow.com/questions/58828456/ionic-4-capacitor-how-to-install-a-cordova-plugin-stepcounter-from-github-wi

Cheers, Gui

**Comment by JoshuaRileyDev** [comment]
I ended up forking the plugin and publishing it to NPM myself and crediting this github repo and you as well, works really well, thanks :)

**Comment by guy-keller** [comment]
All good! Cheers 👍
